"""make crop name and region jointly unique

Revision ID: 0f6ce65e8b62
Revises: f9cca535498a
Create Date: 2025-01-08 17:36:55.396228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6ce65e8b62'
down_revision = 'f9cca535498a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_crop_region', ['crop', 'region'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_constraint('uix_crop_region', type_='unique')

    # ### end Alembic commands ###
